### ISSUE TITLE
Which TBDrain dataset should we download?

### ISSUE THREAD

**Issue by fei88kk** [DL4mHealth/COMET#3]
Dear authors:

Which TBDrain dataset should we download?
<img width="1437" alt="image" src="https://github.com/user-attachments/assets/d809ad5a-b0a5-4bef-979a-b317f33702b9">

**Comment by YiheWang** [comment]
Hi, please download the Full dataset with the CSV extension. All the raw files are in the derivatives folder. Here is a screenshot of the data description. Please also check if they have any updates on the data version and download the same version as ours. 

![image](https://github.com/user-attachments/assets/26437f3d-ff11-45bf-998b-6349a819fd6e)

**Comment by fei88kk** [comment]
Got it, thanks!
